name: twirp_dart_core
description: Core library for using Twirp + Dart
version: 1.0.0
homepage: https://github.com/apptreesoftware/twirp_dart_core
author: Matthew Smith<matthew.smith@apptreesoftware.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.11.0
  requester: ">=0.0.2 <2.0.0"

dev_dependencies:
  test: ^1.0.0
